#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Morito Shunsuke
# SPDX-License-Identifier: GPL-3.0-only

import sys
from PyPDF2 import PdfReader


input_pdf = sys.stdin.readline().strip()


try:
    reader = PdfReader(input_pdf)
except FileNotFoundError:
    sys.exit(1)

for page in reader.pages:
    text = page.extract_text()
    if text:
        print(text)

