#!/usr/bin/env python3
#SPDX-FileCopyrightText: 2025 Morito Shunsuke
#ここにライセンスと著作権について書く



import sys
from PyPDF2 import PdfReader


input_pdf = sys.argv[1]
output_txt = sys.argv[2]



reader = PdfReader(input_pdf)
text = ""
for page in reader.pages:
    text += page.extract_text() + "\n"


with open(output_txt, "w", encoding="utf-8") as f:
    f.write(text)

